---
- hosts: localhost
  become: true
  roles:
    - role: dynatrace.oneagent
  vars_files:
    - ../extra_vars.json
  vars:
    dynatrace_oneagent_host_metadata: environment=prod app=easytravel supportgroup=easyTravel-Support
    dynatrace_oneagent_install_args:
      --set-app-log-content-access: true
      --set-infra-only: false
      --set-host-group: easytravel-production